02
js-tasks-ru/js-20220513_aszuev pull request #2
Opened 2022-05-18 10:57 UTC by Alexanderzu

2022-05-18 10:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-18 11:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-18 11:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-18 11:13 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-19 10:27 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    if (param == 'asc') {
помните что `==` в JS не существует.
Нужно заменить на `===`

2022-05-19 10:27 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        const arrDeskNew =  arrDesk.sort(caseInsensitiveComparatorSort).reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-05-19 10:28 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        return valueALowerCase.toLowerCase().localeCompare(valueBLowerCase.toLowerCase());
`localeCompare` должен принять массив локалей, нет необходимости использовать метод `toLowerCase`
`string1.localeCompare(string2, ['ru', 'en'],`

2022-05-19 10:28 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        const valueALowerCase = valueA.toLowerCase();
здесь следует избавиться от методов `toLowerCase`

2022-05-19 10:29 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +        } else {
этот блок `else` должен просто вернуть 0

2022-05-19 10:29 UTC, dosandk requested changes
необходимо внести правки согласно комментариев

2022-05-19 11:05 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-05-19 11:13 UTC, dosandk approved these changes
👍 good

2022-05-19 11:13 UTC, merged